### ISSUE TITLE
The "./one_big.js" is missing

### ISSUE THREAD

**Issue by ausk** [kkweon/keras-docset#1]
Hi, kkweon, thank you for providing the tool to generate the keras docset.
Today I try to generate the docset with your tool, but it give me an error as follow:
`
Traceback (most recent call last):
  File "preprocess.py", line 39, in <module>
    main()
  File "preprocess.py", line 11, in main
    data = preprocess(filename)
  File "preprocess.py", line 19, in preprocess
    with open('./one_big.js', 'r') as f:
IOError: [Errno 2] No such file or directory: './one_big.js'
`

Clearly, the "./one_big.js" file is missing so that the bash cannot find it, would you please upload the  file named "./one_big.js"? 

Thank you with the best regards!

**Comment by kkweon** [comment]
Hi, thanks for letting me know.
I totally forgot about this.

I pushed a few changes.
From now, it will use customized CSS to preprocess instead of running python.

So if you build it again, it will look like this

![image](https://cloud.githubusercontent.com/assets/2981167/25369714/cae1d590-293a-11e7-8e05-0b274788b393.png)

**Comment by ausk** [comment]
Thank you for update this, now I just get the raw docset for zeal, it's  great!
I cannot help giving my first star for you, best wish!
